services:
  slavarr:
    working_dir: /share/CACHEDEV1_DATA/PlexRoot/ContainerConfig/slavarr
    build: /share/CACHEDEV1_DATA/PlexRoot/ContainerConfig/slavarr
    env_file:
      - /share/CACHEDEV1_DATA/PlexRoot/ContainerConfig/slavarr/.env
    ports:
      - "3001:3001"
    network_mode: host
    volumes:
      - /share/CACHEDEV1_DATA/PlexRoot/ContainerConfig/slavarr/data:/app/data
